### ISSUE TITLE
THIS IS AMAZING.. I love this thing so freaking much... 

### ISSUE THREAD

**Issue by blade93ny** [araujoigor/json-grid#4]
Hey Igor,

This thing is awesome!!!
Exactly what i needed to explore a bunch of complex JSON data... 
Would cool if you could work more on this and extend the functionality...

Any super cool and useful... Thanks a bunch!

**Comment by araujoigor** [comment]
@blade93ny Cheers man! Thanks for the feedback!

If you just need to explore `JSON` objects, maybe you can use the version I just released on my personal website: https://www.araujoigor.com/json-grid. Feel free to give feedback!

With regards to extending the functionalities, I will be probably be working in this project more often in the future. So happy to hear any ideas you might have!
